[workspace]
resolver = "2"
members = [
    "crates/open-king-io",
    "crates/open-king-core",
    "crates/open-king-cli",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
rust-version = "1.75"
license = "MIT"
repository = "https://github.com/Broccolito/open-king"
authors = ["Wanjun Gu"]

[workspace.dependencies]
open-king-io = { path = "crates/open-king-io" }
open-king-core = { path = "crates/open-king-core" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
