[package]
name = "segprobe"
version = "0.1.0"
edition = "2021"

[dependencies]
open-king-io = { path = "../../../../crates/open-king-io" }
open-king-core = { path = "../../../../crates/open-king-core" }
open-king-cli = { path = "../../../../crates/open-king-cli" }

[profile.release]
opt-level = 3

[workspace]
